version: '3'
services:
  db:
    image: postgres
    restart: always
    env_file:
      - .env
    ports:
      - '5432:5432'
    volumes:
      - ./seed.sql:/docker-entrypoint-initdb.d/seed.sql
volumes:
  db:
    driver: local
